import { Inter } from "next/font/google";
import "./globals.css";
import '@mdi/font/css/materialdesignicons.min.css';
import { ClerkProvider } from '@clerk/nextjs'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mbulu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="fr">
        <body className={inter.className}>
          {children}
          <script
            src="../script.js" defer>
          </script>
        </body>
      </html>
    </ClerkProvider>
  );
}
