import { Inter } from "next/font/google";
import "./globals.css";
import '@mdi/font/css/materialdesignicons.min.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mbulu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
      </head>
      <body className={inter.className}>
        {children}
        <script
          src="../script.js" defer>
        </script>
      </body>
    </html>
  );
}
